name: Tests
on:
  push:
    paths:
      - '2019/**'
    branches:
      - master
  pull_request:
    paths:
      - '2019/**'
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      working-directory: 2019/
      run: go test ./...
  lint:
    name: "Run static analysis"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13.x"
    - name: "Installing staticcheck"
      working-directory: 2019/
      run: "GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck"
    - name: Checkout code
      uses: actions/checkout@v1
    - name: "Run Go vet"
      working-directory: 2019/
      run: "go vet ./..."
    - name: "Run static check"
      working-directory: 2019/
      run: "$(go env GOPATH)/bin/staticcheck -go 1.11 ./..."
