name: Python
on:
  push:
    paths:
      - '2015/**'
    branches:
      - master
  pull_request:
    paths:
      - '2015/**'
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        python-version: [ '3.7.x']
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    name: Python ${{ matrix.python-version }}
    steps:
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install Tox
      working-directory: 2015/
      run: pip install tox
    - name: Run Tests
      working-directory: 2015/
      run: tox -e py37
    - name: Run Mypy
      working-directory: 2015/
      run: tox -e mypy
    - name: Run linting
      working-directory: 2015/
      run: tox -e lint

