name: Python
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        python-version: [ '3.x', 'pypy3' ]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    name: Python ${{ matrix.python-version }}
    steps:
    - name: Install Python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install Tox
      working-directory: 2015/
      run: pip install tox
    - name: Run Tox
      working-directory: 2015/
      run: tox -e py37,mypy,lint -p all

